### ISSUE TITLE
CSS样式化文字

### ISSUE THREAD

**Issue by sysong13** [sysong13/web-front-end#2]
- [x] 基础文字与字体样式化

- [x] 样式化列表

- [x] 样式化链接

**Comment by sysong13** [comment]
## 基本文字样式

- 颜色 `color:red;`
- 字体 `font-family:"Trebuchet MS", Verdana, sans-serif;`  
  

> 在这种情况下，浏览器从列表的第一个开始，然后查看在当前机器中，这个字体是否可用。如果可用，就把这个字体应用到选中的元素中。如果不可用，它就移到列表中的下一个字体，然后再检查。  
在字体栈的最后提供一个合适的通用的字体名称是个不错的办法，这样的话，即使列出的字体都无法使用，浏览器至少可以提供一个还算合适的选择。为了强调这一点，如果没有其他选项可用，那么段落将被赋予浏览器的默认衬线字体 - 通常是Time New Roman - 这对于 sans-serif 字体是不利的！

- 字体大小 `font-size:10px;  font-size:1em;`   
**它是一个继承属性**： 从父元素继承，所以这一切都是从整个文档的根元素——`<html>`开始，浏览器的 font-size 标准设置的值为 16px。

> 其他元素也许有默认的大小，比如` <h1> `元素有一个 2ems 的默认值，所以它的最终大小值为 32px。当你开始更改嵌套元素的字体大小时，事情会变得棘手。比如，如果你有一个 `<article> `元素在你的页面上，然后设置它的 font-size 为 1.5ems (通过计算，可以得到大小为 24px)，然后想让 `<article>` 元素中的段落获得一个计算值为 20px 的大小，那么你应该使用20/24 em。
### 字体样式，字体粗细，文本转换和文本装饰
- `font-style`:用来打开和关闭文本 italic (斜体)。 可能的值如下 (你很少会用到这个属性，除非你因为一些理由想将斜体文字关闭斜体状态)：  
    - `normal`:普通字体
    - `italic`: 文本设置为斜体  相当于标签`<i></i>的效果
    - `oblique`: 
- `font-weight`:设置文字的粗体大小。  
    - `normal`,`bold`:普通或加粗
- `text-transform`: 设置要转换的字体：
    - `none`  `uppercase`  `lowercase`  `capitalize`  `full-width`:将所有字形转换成固定宽度的正方形，类似于等宽字体，允许对齐
- `text-decoration`: 设置文本的下划线等装饰
    - `none`  `underline`  `overline`  `line-through`
- `text-shadow`:文字阴影  
   `text-shadow: 4px 4px 5px red;`  最多四个属性：  
   1.  水平偏移  必选，正数向右
   2.  垂直偏移  必选
   3.  模糊半径  可选
   4.  颜色 可选，默认为黑色

### 文本布局

- 文本对齐 `text-align`:   
     - `left`  `right`  `center`  `justify`
- 行高 `line-height`:  `line-height:1.5`
- 字母间距 `letter-spacing`
- 词汇间距 `word-spacing`
- 文本缩进 `text-indent`

**Comment by sysong13** [comment]
## 列表样式
`<ul>  <ol> <dl>`  
`<ul>`和`<ol>`元素设置`margin`的顶部和底部: 16px(1em) 0，和padding-left: 40px(2.5em)；  
###列表特定样式
- `list-style-type`:符号样式，设置用于列表的项目符号的类型，例如无序列表的方形或圆形项目符号，或有序列表的数字，字母或罗马数字  
[样式取值](https://developer.mozilla.org/zh-CN/docs/Web/CSS/list-style-type) 
- `list-style-position`:设置在每个项目开始之前，项目符号是出现在列表项内，还是出现在其外。
         `list-style-position:inside` 符号和下一行文字对齐
         `list-style-position:outside` 
- `list-style-image`: 允许您为项目符号使用自定义图片，而不是简单的方形或圆形(但是一般用`backgroun-image`取代，因为它的可调属性更多。  
       `list-style-image:url(star.svg);`
```CSS
ul li {
  padding-left: 2rem;
  background-image: url(star.svg);
  background-position: 0 0;  //背景图片相对内边界左、上的距离，0 0即项目最左上测
  background-size: 1.6rem 1.6rem;
  background-repeat: no-repeat;   //repeat  背景图片不断复制直到填满整个背景空间}

```

**Comment by sysong13** [comment]
## 样式化链接
`<a href="#"></a>`  
链接具有一些默认样式：
  -  链接具有下划线。
  - 未访问过的 (Unvisited) 的链接是蓝色的。
  - 访问过的 (Visited) 的链接是紫色的.
  - 悬停 (Hover) 在一个链接的时候鼠标的光标会变成一个小手的图标。
  - 选中 (Focus) 链接的时候，链接周围会有一个轮廓，你应该可以按 tab 来选中这个页面的链接 (在 Mac 上, 你可能需要使用Full Keyboard Access: All controls 选项，然后再按下 Ctrl + F7 ，这样就可以起作用)
  - 激活 (Active) 链接的时候会变成红色 (当你点击链接时，请尝试按住鼠标按钮。)
``` CSS
a {

}


a:link {

}

a:visited {

}

a:focus {

}

a:hover {

}

a:active {

}
```
> 这个顺序是重要的，因为链接的样式是建立在另一个样式之上的，比如第一个规则的样式会应用到所有后续的样式，如果当一个链接被激活 (activated) 的时候，它也是处于悬停 (hover) 状态的。如果你搞错了顺序，那么就可能不会产生正确的效果。要记住这个顺序，你可以尝试这样帮助记忆：LoVe Fears HAte.

### 在链接中包含图标
做法和列表标识符相似，使用background属性
``` CSS
a[href*="http"] {
  background: url('https://mdn.mozillademos.org/files/12982/external-link-52.png') no-repeat 100% 0;   // 背景出现在链接最右上侧
  background-size: 16px 16px;
  padding-right: 19px;  //为图标留位置
}
```
###链接经常与列表共用
`<li><a href="#">Home</a></li>`
默认情况下，li和a的margin为0,即二者看起来在一个框内；
`<a>`选择器设置连接各种状态和样式；  
`<li>`选择器设置位置；
